[package]
name = "non-fungible-token"
version = "1.1.0"
authors = ["David Tanaka <realhardworkingdeveloper@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
rand = "0.7.3"
near-contract-standards = "3.1.1"
